version: '3'

### environment variables

services:
    fast_metadata_search_service: 
        build: .
        image: fast_metadata_search_service
        environment:
            PYTHONUNBUFFERED: 1
            DUPLICATE_CHECKING_SERVICE_ADDRESS_LIST: http://document_prefetch_service_overall_arxiv:8060/check-duplicate,http://document_prefetch_service_overall_pmcoa:8060/check-duplicate,http://document_prefetch_service_overall_s2orc:8060/check-duplicate
        networks:
            - common_network
        hostname: fast_metadata_search_service
        # ports:
        #     - 8028:8060
networks:
    common_network:
        external: true