version: '3'

### environment variables

services:
    final_api_gateway_service: 
        build: .
        image: final_api_gateway_service
        environment:
            PYTHONUNBUFFERED: 1
            HELPER_FUNCTIONS_SERVICE_ADDRESS: http://helper_functions_service:8060/process
            PAPER_DATABASE_SERVICE_ADDRESS: http://paper_database_service:8060/get-papers
            CITATION_FORMATTING_SERVICE_ADDRESS: http://citation_formating_service:8060/citation-formatting-service
            CITATION_GENERATION_SERVICE_ADDRESS: http://citation_generation_service:8060/generate-citation
            EXTRACTIVE_SUMMARIZATION_SERVICE_ADDRESS: http://extractive_summarization_service:8060/extractive-summarize
            DOCUMENT_SEARCH_ADDRESS: http://document_search_overall_service:8060/document-search
            TITLE_GENERIC_SEARCH_ADDRESS: http://title_generic_search_service:8060/title-generic-search
        networks:
            - common_network
        hostname: final_api_gateway_service
        ports:
            - 8060:8060
networks:
    common_network:
        external: true