version: '3'

services:
    
    paper_database_manager:
        build: ./src/modules/paper_database
        image: paper_database_manager
        command: ["echo","hello"]
        
    document_prefetch_build_database_s2orc:
        build: ./src/build_database/S2ORC
        image: document_prefetch_build_database_s2orc
        environment:
            NUM_PROCESSES: 100
            COLLECTION: S2ORC
        volumes:
            - $PWD/data/S2ORC:/app/data
